---
project:
  groupId: robinschuerer
  artifactId: spring-boot-webservice-loom
  version: 1.0.0-SNAPSHOT
plugins:
  - junit4
dependencies:
  - io.springfox:springfox-swagger2:2.7.0
  - io.springfox:springfox-swagger-ui:2.7.0
  - org.springframework.boot:spring-boot-starter-web:1.5.3.RELEASE
  - org.springframework.boot:spring-boot-starter-actuator:1.5.3.RELEASE
testDependencies:
  - junit:junit:4.12
